include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    avoid_print: false  
    prefer_single_quotes: true
    use_key_in_widget_constructors: false
    prefer_const_constructors: false

analyzer:
  errors:
    prefer_const_constructors: error
    use_key_in_widget_constructors:
